"""
A Python module implemented in Rust.

pyrs-yaml: high-performance YAML parsing with perfect round-trip support.
"""

from _typeshed import Incomplete
from typing import Any, final

@final
class StreamIterator:
    def __iter__(self, /) -> StreamIterator: ...
    def __next__(self, /) -> dict |None: ...

@final
class YAML:
    def __new__(cls, /, typ: "str" = "rt", schema: "str" = "core", max_depth: "int" = 1000, allow_duplicate_keys: "bool" = False) -> YAML: ...
    def parse(self, /, yaml: "str | bytes") -> "YamlDocument": ...
    def parse_all_docs(self, /, yaml: "str") -> "list[YamlDocument]": ...
    def parse_file(self, /, path: "str") -> "YamlDocument": ...
    def safe_load(self, /, yaml: "str") -> "dict[str, Any] | list[Any]": ...
    def safe_loads(self, /, yaml: "str") -> "list[dict[str, Any] | list[Any]]": ...

@final
class YamlDocument:
    def __contains__(self, /, key: str) -> bool: ...
    def __delitem__(self, /, key: str) -> None: ...
    def __getitem__(self, /, key: Any) -> Any: ...
    def __iter__(self, /) -> Any: ...
    def __len__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...
    def __setitem__(self, /, key: str, value: Any) -> None: ...
    def __str__(self, /) -> str: ...
    def _append_path(self, /, segments: "list", value: "Any") -> "None": ...
    def _delete_path(self, /, segments: "list") -> "None": ...
    def _insert_path(self, /, segments: "list", index: "int", value: "Any") -> "None": ...
    def _rename_path(self, /, segments: "list", new_key: "str") -> "None": ...
    def _revision(self, /) -> int: ...
    def _set_path(self, /, segments: "list", value: "Any") -> "None": ...
    def flush_source(self, /) -> None:
        """
        Lazily re-serialize the AST into `source` if edits have occurred.
        """
    def get(self, /, key: "str", default: "Any" = None) -> "Any": ...
    def reparse(self, /, resolve_merges: "bool" = True, schema: "str" = "core") -> "None": ...
    def root_type(self, /) -> str: ...
    def source(self, /) -> str: ...
    def to_dict(self, /) -> Any:
        """
        将文档转换为 Python 字典/列表，自动解析锚点引用。
        """
    def to_json(self, /, indent: "int" = 2) -> "str": ...
    def to_yaml(self, /) -> str:
        """
        将文档序列化为 YAML 字符串（默认 2 空格缩进）。
        """
    def to_yaml_with_options(self, /, indent_size: "int" = 2, explicit_start: "bool" = False, explicit_end: "bool" = False, sort_keys: "bool" = False, max_depth: "int" = 1000, width: "int" = 80, indent_mapping: "int | None" = None, indent_sequence: "int | None" = None, indent_offset: "int | None" = None) -> "str": ...
    def validate(self, /, schema: "str | dict[str, Any]") -> "None": ...
    def version(self, /) -> str: ...

def clear_tag_handlers() -> None: ...
def detect_language() -> "str": ...
def dump_file(data: "Any", path: "str") -> "None": ...
def from_dict(data: "dict[str, Any] | list[Any]") -> "str": ...
def from_json(json_str: "str") -> "str": ...
def get_language() -> "str": ...
def list_languages() -> "list[str]": ...
def negotiate_language(user_locales: "list[str]", default: "str" = "en") -> "str": ...
def parse(yaml: "str | bytes", resolve_merges: "bool" = True, schema: "str" = "core", max_depth: "int" = 1000, allow_duplicate_keys: "bool" = False) -> "YamlDocument": ...
def parse_all_docs(yaml: "str", resolve_merges: "bool" = True, schema: "str" = "core", max_depth: "int" = 1000, allow_duplicate_keys: "bool" = False) -> "list[YamlDocument]": ...
def parse_file(path: "str", schema: "str" = "core", max_depth: "int" = 1000, allow_duplicate_keys: "bool" = False) -> "YamlDocument": ...
def parse_stream(yaml: "str | bytes", on_event: "Callable[[dict[str, Any]], bool] | None" = None) -> "StreamIterator | None": ...
def read_markdown(path: "str", schema: "str" = "core") -> "tuple[dict[str, Any] | None, str]": ...
def read_markdown_str(content: "str", schema: "str" = "core") -> "tuple[dict[str, Any] | None, str]": ...
def register_tag(name: "str", handler: "Py<PyAny>", priority: "u32" = 0) -> None: ...
def remove_tag(name: "str") -> None: ...
def safe_dump(data: "dict[str, Any] | list[Any]") -> "str": ...
def safe_load(yaml: "str", schema: "str" = "core", max_depth: "int" = 1000, allow_duplicate_keys: "bool" = False) -> "dict[str, Any] | list[Any]": ...
def safe_loads(yaml: "str", schema: "str" = "core", max_depth: "int" = 1000, allow_duplicate_keys: "bool" = False) -> "list[dict[str, Any] | list[Any]]": ...
def set_language(lang: "str") -> "None": ...
def __getattr__(name: str) -> Incomplete: ...
