#!/usr/bin/env python3
"""Assert that a hand-typed signature on a published API page says what the library says.

Measured through the built site, not guessed: `docs/en/api/reference.md:493` types
`parse_stream(yaml: str) -> StreamIterator`, while the stub that ships inside every wheel declares
`parse_stream(yaml: str | bytes, on_event=None, max_depth=1000) -> StreamIterator | None`. Same page, same name,
two claims - and the site builds green because a wrong signature is still valid HTML.

Why the authority is the running package. The stub is generated by maturin from an import of the extension, and
the editing surface of `YamlDocument` plus the whole of `Node` / `MergedView` are attached from Python afterwards,
so they are on the object and not in the `.pyi` (measured: 13 members missing from the declared
`YamlDocument`, `Node` and `MergedView` absent entirely). A checker that read only the stub would report the
documentation as wrong where the documentation is right - the failure mode that makes a gate ignored rather than
obeyed. So names and parameters come from the shipped package, and the stub's own gap is a separate finding, not
this one's input.

The rule is deliberately sound rather than exhaustive: a block is a finding only when **no** declaration in the
library matches it. `parse` exists as a module function and as `YAML.parse` with different parameters, so a page
showing either one is correct; a page showing a parameter list neither one has is wrong whichever way it resolves.

Usage:
    python scripts/check_doc_signatures.py            # all four locales
    python scripts/check_doc_signatures.py docs/en/api/reference.md

Exit code 0 = every typed signature matches some declaration; 1 = a contradiction; 2 = the checker could not read
its own source of truth (the extension is importable, and a checker that silently skips that check is worse than
none).
"""

from __future__ import annotations

import argparse
import inspect
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
PACKAGE = REPO / "python" / "pyrs_yaml"
DOCS = REPO / "docs"
LOCALES = ("en", "ja", "ko", "zh")

CALL_SHAPE = re.compile(r"^(?P<name>[A-Za-z_][A-Za-z0-9_.]*)\((?P<args>.*)\)\s*(?:->.+)?$")
FENCE = re.compile(r"^```(?:python|py)?\s*$")
DECLARATION = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*\s*(?::[^=]+)?(?:=.*)?$")
DIRECTIVE = re.compile(r"^:::\s+(?P<path>\S+)", re.M)


def signature_parameters(function: object) -> tuple[list[str], set[str]] | None:
    """The parameter names the shipped object accepts, and which of them have defaults.

    Positional-only, keyword-only and `*args` / `**kwargs` are kept, because a document that omits one is hiding a
    parameter the caller can pass - the exact form the measured defect takes.
    """
    try:
        sig = inspect.signature(cast_function(function))
    except (TypeError, ValueError):
        return None
    names = []
    defaulted = set()
    for parameter in sig.parameters.values():
        if parameter.name == "self":
            continue
        if parameter.kind is inspect.Parameter.VAR_POSITIONAL:
            names.append(f"*{parameter.name}")
        elif parameter.kind is inspect.Parameter.VAR_KEYWORD:
            names.append(f"**{parameter.name}")
        else:
            names.append(parameter.name)
        if parameter.default is not inspect.Parameter.empty:
            defaulted.add(parameter.name)
    return names, defaulted


def cast_function(function: object):
    """Unwrap what `getattr` hands back, so `@staticmethod` / `@classmethod` / `@property` still answer."""
    if isinstance(function, (staticmethod, classmethod)):
        return function.__func__
    if isinstance(function, property):
        return function.fget
    return function


PUBLISHED_DUNDERS = (
    "__init__",
    "__next__",
    "__iter__",
    "__enter__",
    "__exit__",
    "__repr__",
    "__str__",
    "__getitem__",
    "__setitem__",
    "__delitem__",
    "__contains__",
    "__len__",
    "__bool__",
)


def inventory() -> dict[str, list[tuple[list[str], set[str]]]]:
    """Every callable the shipped package offers: module functions, and members of every exported class.

    Keyed by the bare name (so `parse` collects the module function and `YAML.parse`) and by `Class.method`, which
    is how a page can name the owner explicitly. Each entry is the parameter list plus the names that have
    defaults, because "this document drops a parameter" is only harmless when the dropped one is optional.
    """
    try:
        import pyrs_yaml
    except ImportError as exc:  # pragma: no cover - the gate reports, never shrugs
        raise RuntimeError(f"cannot import the package under test: {exc}") from exc

    found: dict[str, list[tuple[list[str], set[str]]]] = {}

    def add(prefix: str, name: str, params: tuple[list[str], set[str]]) -> None:
        found.setdefault(name, []).append(params)
        if prefix:
            found.setdefault(f"{prefix}.{name}", []).append(params)

    classes = []
    for attr in sorted(dir(pyrs_yaml)):
        if attr.startswith("_"):
            continue
        value = getattr(pyrs_yaml, attr)
        if inspect.isclass(value):
            classes.append((attr, value))
            continue
        if callable(value):
            params = signature_parameters(value)
            if params is not None:
                add("", attr, params)

    for cls_name, cls in classes:
        for attr in sorted(dir(cls)):
            if attr.startswith("_") and attr not in PUBLISHED_DUNDERS:
                continue
            try:
                value = getattr(cls, attr)
            except AttributeError:
                continue
            if not (callable(value) or isinstance(value, (staticmethod, classmethod, property))):
                continue
            params = signature_parameters(value)
            if params is not None:
                add(cls_name, attr, params)
    return found


def split_parameters(text: str) -> list[str] | None:
    """The parameter names a document writes, or `None` when the block is not a declaration list.

    `register_tag("!custom", handler_fn, priority=1)` is a call with values, not a signature: it documents usage
    and is not the thing this checker can compare.
    """
    parts, depth, current = [], 0, []
    for char in text:
        if char in "([{":
            depth += 1
        elif char in ")]}":
            depth -= 1
        elif char == "," and depth == 0:
            parts.append("".join(current))
            current = []
            continue
        current.append(char)
    if "".join(current).strip():
        parts.append("".join(current))
    names = []
    for part in parts:
        part = part.strip()
        if not part:
            continue
        if part in ("*", "**"):
            continue
        head = re.split(r"[:=]", part, maxsplit=1)[0].strip()
        if head.startswith(("'", '"')):
            return None  # a literal argument: this is an example call
        if not re.match(r"^(\*{0,2})[A-Za-z_][A-Za-z0-9_]*$", head):
            return None
        names.append(head)
    return names or None


def typed_blocks(page: pathlib.Path) -> list[tuple[int, str, list[str]]]:
    """Fenced blocks whose entire body is one declaration-shaped signature."""
    lines = page.read_text(encoding="utf-8").splitlines()
    out = []
    index = 0
    while index < len(lines):
        if FENCE.match(lines[index].strip()):
            start = index + 1
            cursor = start
            while cursor < len(lines) and not lines[cursor].strip().startswith("```"):
                cursor += 1
            body = [ln.strip() for ln in lines[start:cursor] if ln.strip()]
            if len(body) == 1:
                match = CALL_SHAPE.match(body[0])
                if match:
                    first = match.group("args").split(",")[0].strip()
                    if first and DECLARATION.match(first):
                        written = split_parameters(match.group("args"))
                        if written is not None:
                            out.append((index + 2, match.group("name"), written))
            index = cursor
            continue
        index += 1
    return out


def is_faithful(written: list[str], candidates: list[tuple[list[str], set[str]]]) -> bool:
    """Whether the document says something the library really accepts.

    Two shapes are true: the exact parameter list, and a prefix of one whose dropped parameters all have
    defaults - the abbreviation a reference page legitimately uses. Anything else names a parameter the object
    does not accept, reorders it, or hides a required one.
    """
    for declared, defaulted in candidates:
        if written == declared:
            return True
        dropped = declared[len(written) :]
        if declared[: len(written)] == written and all(name in defaulted for name in dropped):
            return True
    return False


def display(page: pathlib.Path) -> str:
    """The path as a reader wants it: inside the repository relative, anywhere else as given."""
    try:
        return page.relative_to(REPO).as_posix()
    except ValueError:
        return page.as_posix()


def check(pages: list[pathlib.Path], table: dict) -> list[str]:
    findings = []
    for page in pages:
        for line, name, written in typed_blocks(page):
            candidates = table.get(name) or table.get(name.split(".")[-1])
            if candidates is None:
                # A name the shipped package does not offer: nothing to contradict. That is a separate blind
                # spot - a page documenting an API that is not there - and it belongs in the matrix, not here.
                continue
            if is_faithful(written, candidates):
                continue
            widest = max(candidates, key=lambda entry: len(entry[0]))[0]
            findings.append(
                f"{display(page)}:{line} types {name}({', '.join(written)}) "
                f"but the shipped object accepts {name}({', '.join(widest)})"
                + ("" if len(candidates) == 1 else f"  [{len(candidates)} declarations]")
            )
    return findings


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("pages", nargs="*", help="API pages to check (default: all four locales)")
    args = parser.parse_args(argv)

    pages = (
        [pathlib.Path(p) for p in args.pages]
        if args.pages
        else sorted(p for loc in LOCALES for p in (DOCS / loc / "api").glob("*.md"))
    )
    try:
        table = inventory()
    except RuntimeError as exc:
        print(f"cannot measure: {exc}", file=sys.stderr)
        return 2
    if not table:
        print("cannot measure: the library declares no callables", file=sys.stderr)
        return 2
    findings = check(pages, table)
    checked = sum(len(typed_blocks(p)) for p in pages)
    if not findings:
        print(
            f"OK: {checked} typed signature block(s) across {len(pages)} page(s) match a real declaration "
            f"({len(table)} names known)"
        )
        return 0
    print(f"{len(findings)} hand-typed signature(s) contradict the library:", file=sys.stderr)
    for finding in findings:
        print(f"  {finding}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
