#!/usr/bin/env python3
"""Instruction-count gate: measure the engine's hot paths in counted
instructions (`callgrind` Ir) and compare them against a committed baseline.

Why: the divan suite reports through CodSpeed, which compares today's runner
against a baseline recorded on different hardware. For sub-10% effects that
number is not reproducible — three pushes that each did strictly *less* work
reported -7.7%, -10.5%, -9.8% for the same benchmark set. `callgrind` Ir repeats
to within 0.004% on the same binary, so a committed baseline can gate a real
one-percent tolerance. See `crates/pyrs-yaml-core/benches/ir_gate.rs` for the
measurement method (setup-only pass subtracted out, fixed iteration count).

Usage:
    python scripts/ir_gate.py                 # measure and gate
    python scripts/ir_gate.py --update        # re-measure, rewrite the baseline
    python scripts/ir_gate.py --only serialize_small --only parse_medium
    python scripts/ir_gate.py --tolerance 0.02
    python scripts/ir_gate.py --report-only   # measure, never fail (diagnostics)

Requires valgrind. On this development box run it inside WSL:
    wsl -e bash -lc "python3 /mnt/d/PycharmProjects/pyrs-yaml/scripts/ir_gate.py"
"""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import platform
import re
import subprocess
import sys
import tempfile

REPO = pathlib.Path(__file__).resolve().parent.parent
BASELINE = REPO / ".ci" / "ir-baseline.json"
CRATE = "pyrs-yaml-core"
BENCH = "ir_gate"

# Calibrated by measurement, and twice recalibrated by measurement that refuted the earlier
# explanation.
#
# Repeat precision, same binary: ~0.001% (worst ±5,000 instructions on a 358M scenario).
# Cross-image precision on the enforcing environment, measured over two GitHub runner images
# (ubuntu-24.04 20260927.320.1 and 20261004.327.1) on the same commit: every one of the twelve
# scenarios agrees to at most 0.0018% (`parse_anchors`, 6,061 instructions on 341M). That is the
# number the tolerance is now sized from: 0.5% is ~280x the widest observed spread, and it is a
# real line rather than a shrug - a 0.5% instruction regression is a meaningful one.
#
# What the 2% used to be: the gap between a baseline generated in WSL and the same code measured
# on a runner. `serialize_block_scalars` reads +0.78% in WSL and +2.23% here, a 1.45% difference
# that `ir_gate.py` attributed to "the dynamic loader and malloc of the host image", and the
# tolerance was sized around that. Two explanations were tested. (1) The suspicion that
# `.gitattributes` was normalising the CR bytes inside `BLOCK_SCALAR_YAML` on checkout: adding
# `-text` changed the runner's number by 28 instructions out of 16,020,906 - REFUTED. The probe did
# find something, just not that: `git show` holds this fixture with no CR bytes on `main` and with 98
# on the branch that added `-text`, so the stored bytes of the measured input depended on which tree
# the last author committed. `-text` fixes that (tree == commit, asserted by
# `tests/test_line_endings_gate.py`), and stripping the CRs from a tree moves `serialize_anchors` by
# 0.86% while leaving `serialize_block_scalars` 1.45% off the runner. (2) Drift between runner
# images: stable, +2.23% on both, agreeing to 0.0018%. So the cross-machine difference is real,
# scenario-specific and still unexplained - which is precisely why the committed numbers are now
# generated by the environment that enforces them, and why `generated_by` is written into the
# baseline file.
#
# If this gate is ever run somewhere other than the environment recorded below, expect a
# percentage-point of drift on the allocation-heavy scenarios and treat a marginal failure as a
# hint to re-measure, not to widen the line. `--update` regenerates both numbers and provenance.
DEFAULT_TOLERANCE = 0.005


def environment() -> str:
    """A one-line description of where this measurement came from.

    Recorded in the baseline so the two cannot be read apart later. `ImageOS`/`ImageVersion` are set
    by GitHub Actions runners; a local run gets the host platform instead, which is how a WSL- or
    macOS-generated baseline becomes visible in the gate's own output rather than silently trusted.
    """
    image = os.environ.get("ImageOS")  # noqa: SIM112 - the name comes from the runner, not from us
    version = os.environ.get("ImageVersion")  # noqa: SIM112 - ditto; uppercasing it reads a blank
    if image and version:
        return f"github-runner {image}, image {version}"
    return f"{platform.system()} {platform.release()} ({platform.machine()})"


def run(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    """Never `shell=True`: argument quoting has burned this project before."""
    return subprocess.run(cmd, check=False, text=True, **kw)


def build_exe() -> str:
    """Return the release benchmark binary, via cargo's JSON so no filename
    guessing (hash suffixes change with every build).

    `--features ir-gate` is the only way this target is built: it carries
    `required-features`, which keeps it out of every default build — including
    `cargo codspeed run`, which executes each discovered benchmark with no
    arguments and would otherwise trip the binary's usage error.
    """
    res = run(
        [
            "cargo",
            "bench",
            "-p",
            CRATE,
            "--bench",
            BENCH,
            "--features",
            "ir-gate",
            "--no-run",
            "--message-format=json",
        ],
        capture_output=True,
        cwd=REPO,
    )
    if res.returncode != 0:
        sys.exit(f"build failed:\n{res.stderr[-2000:]}")
    for line in res.stdout.splitlines():
        try:
            msg = json.loads(line)
        except json.JSONDecodeError:
            continue
        exe = msg.get("executable")
        if exe and f"{BENCH}-" in pathlib.Path(exe).name:
            return exe
    sys.exit("cargo did not report an ir_gate executable")


def callgrind_total(exe: str, args: list[str]) -> int:
    """Run `exe args` under callgrind and return the process-wide Ir total."""
    with tempfile.TemporaryDirectory() as tmp:
        out = pathlib.Path(tmp) / "cg.out"
        res = run(
            [
                "valgrind",
                "--tool=callgrind",
                f"--callgrind-out-file={out}",
                "--quiet",
                "--quiet",
                exe,
                *args,
            ],
            capture_output=True,
        )
        if res.returncode != 0:
            sys.exit(f"valgrind failed on {args}:\n{res.stderr[-1500:]}")
        text = out.read_text(encoding="utf-8", errors="replace")
    totals = re.findall(r"^summary:\s+(\d+)", text, re.MULTILINE)
    if not totals:
        sys.exit(f"no callgrind summary for {args}")
    return int(totals[-1])


def loop_instructions(exe: str, scenario: str) -> int:
    """Counted instructions of the measured loop alone: same binary, twice, and
    the setup-only pass subtracted out."""
    full = callgrind_total(exe, [scenario])
    setup = callgrind_total(exe, [scenario, "--setup-only"])
    return full - setup


def rustc_banner() -> str:
    return run(["rustc", "-V"], capture_output=True).stdout.strip()


def rustc_short(banner: str) -> str:
    """Just the version token, so the baseline's two toolchain fields cannot disagree."""
    parts = banner.split()
    return parts[1] if len(parts) > 1 else banner


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--update", action="store_true", help="rewrite the baseline")
    ap.add_argument("--only", action="append", default=[], help="scenario filter")
    ap.add_argument(
        "--tolerance",
        type=float,
        default=None,
        help="allowed growth over baseline; defaults to the baseline's tolerance_hint",
    )
    ap.add_argument("--report-only", action="store_true", help="print measurements, never fail")
    args = ap.parse_args()

    exe = build_exe()
    listed = run([exe, "--list"], capture_output=True).stdout.split()
    scenarios = [s for s in listed if not args.only or s in args.only]
    toolchain = rustc_banner()

    measured = {s: loop_instructions(exe, s) for s in scenarios}

    if args.update:
        # `--update --only X` used to write a baseline containing *only* X: every other
        # scenario's number vanished, and the next gate run reported them as unbaselined.
        # A partial re-measurement therefore merges into what is committed, and refuses to
        # pretend it knows a number it did not measure. A scenario the bench no longer
        # lists is dropped rather than kept as decoration.
        previous: dict[str, int] = {}
        if args.only:
            if not BASELINE.exists():
                sys.exit(f"--update --only needs the existing baseline at {BASELINE}; it is missing")
            previous = dict(json.loads(BASELINE.read_text(encoding="utf-8"))["scenarios"])
        final: dict[str, int] = {}
        for name in listed:
            if name in measured:
                final[name] = measured[name]
            elif name in previous:
                final[name] = previous[name]
            else:
                sys.exit(f"baseline would be incomplete: no number for {name!r} - drop --only or measure it too")
        BASELINE.parent.mkdir(exist_ok=True)
        payload = {
            "toolchain": toolchain,
            "generated_by": {"environment": environment(), "rustc": rustc_short(toolchain), "tool": "callgrind"},
            "tolerance_hint": args.tolerance if args.tolerance is not None else DEFAULT_TOLERANCE,
            "scenarios": final,
        }
        BASELINE.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n")
        print(f"wrote {BASELINE.relative_to(REPO)} ({len(final)} scenarios)")
        return 0

    if not BASELINE.exists():
        print(f"no baseline at {BASELINE.relative_to(REPO)}; run --update first")
        return 1

    ref = json.loads(BASELINE.read_text(encoding="utf-8"))
    origin = ref.get("generated_by", {}).get("environment", "unrecorded")
    here = environment()
    print(f"baseline generated by: {origin}")
    if origin != "unrecorded" and origin != here:
        print(
            f"  note: this run is on {here!r}, which is not the recorded environment. "
            "A WSL-generated number was measured 1.45% off the runner's on "
            "`serialize_block_scalars`; treat a marginal failure as a reason to re-measure."
        )
    if args.report_only:
        for s, ir in measured.items():
            print(f"{s:26} {ir:12,}")
        return 0

    failures: list[str] = []
    # The tolerance travels with the baseline: a hint recorded at generation time
    # is what the enforcing run should honour, otherwise a change to either file
    # silently re-tunes the gate.
    tol = args.tolerance if args.tolerance is not None else float(ref.get("tolerance_hint", DEFAULT_TOLERANCE))
    if ref.get("toolchain") != toolchain:
        failures.append(
            f"toolchain changed: baseline recorded on {ref.get('toolchain')!r}, "
            f"now {toolchain!r}; re-run --update deliberately"
        )
    print(f"{'scenario':26} {'baseline':>13} {'now':>13} {'delta':>9}")
    for s, ir in measured.items():
        base = ref["scenarios"].get(s)
        if base is None:
            failures.append(f"{s}: not in baseline (added without --update)")
            print(f"{s:26} {'-':>13} {ir:13,} {'new':>9}")
            continue
        growth = (ir - base) / base
        print(f"{s:26} {base:13,} {ir:13,} {growth:+9.2%}")
        if growth > tol:
            failures.append(f"{s}: +{growth:.2%} over baseline (tolerance {tol:.2%})")

    if failures:
        print("\n" + "\n".join(f"FAIL  {f}" for f in failures))
        print("\nIf this change is intended, re-baseline deliberately:\n  python scripts/ir_gate.py --update")
        return 1
    print("OK: every scenario within tolerance of the committed baseline")
    return 0


if __name__ == "__main__":
    sys.exit(main())
