name: CodSpeed

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    name: Rust benchmarks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"
      - name: Setup Rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed
      - name: Build the benchmark target(s)
        run: cargo codspeed build
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v5
        with:
          mode: simulation
          run: cargo codspeed run

  python:
    name: Python benchmarks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Create virtualenv
        run: uv venv .venv
      - name: Build and install
        uses: PyO3/maturin-action@v1
        with:
          command: develop
          args: --release
      - name: Install Python benchmark dependencies
        run: uv pip install -q -r .ci/requirements-test.txt
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v5
        with:
          mode: simulation
          run: >
            uv run --no-sync pytest --codspeed -m "benchmark"